apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: technical-test
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 3
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: myapp:latest # update with the deployed image
        imagePullPolicy: Never # for local testing
        ports:
        - containerPort: 5000